apiVersion: v1
kind: Namespace
metadata:
  name: demo-db
  labels:
    app: database
    k10/backup: "enabled"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: demo-db
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass123"
  MYSQL_DATABASE: "pocdb"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: demo-db
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        storageClassName: csi-hostpath-sc
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: demo-db
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306
